name: Deploy S3 Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-s3-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install
        run: yarn --prefer-offline
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}

      - name: Build
        run: yarn build
        env:
          CORS_PROXY_SERVER: https://cors.dev.xrcloud.belivvr.com
          BASE_ASSETS_PATH: https://assets-test.dev.xrcloud.belivvr.com/hubs/
          RETICULUM_SERVER: https://reticulum.dev.xrcloud.belivvr.com
          THUMBNAIL_SERVER: https://nearspark.xrcloud.belivvr.com
          NON_CORS_PROXY_DOMAINS: hubs.local,stage.reticulum.io,hubs-upload-cdn.com,hubs.belivvr.com,hubs-alpha.belivvr.com,assets.stage.xrcloud.belivvr.com,assets-test.dev.xrcloud.belivvr.com,reticulum.stage.xrcloud.belivvr.com,reticulum.dev.xrcloud.belivvr.com
          MEDIA_SERVER: https://reticulum.dev.xrcloud.belivvr.com

      - name: Deploy S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: assets-test.dev.xrcloud.belivvr.com/hubs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.A`WS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'
